### ISSUE TITLE
Where i can edit color of main menu stuff?

### ISSUE THREAD

**Issue by Blueberryy** [Gaerisson/Gmod-Custom-Menu#3]
just say folder where i can find it

**Comment by Gaerisson** [comment]
You mean the color of buttons in main menu ?

**Comment by Gaerisson** [comment]
![image](https://user-images.githubusercontent.com/25458928/65362457-ba4cfc00-dc07-11e9-820e-50f4c221f29f.png)
Gmod-Custom-Menu\garrysmod\html\css\menu\**Menu.css**

**Comment by Blueberryy** [comment]
Yeah,  and with it i want to know how to edit following stuff

![kMILKK4UY4](https://user-images.githubusercontent.com/36592509/65367993-9dd6b100-dc53-11e9-8319-2dc07a834b7b.png)
1 - Small line  color
2 - Title text color
3 - Icon color
4 - Background color
