### ISSUE TITLE
Removing the servers from bottom

### ISSUE THREAD

**Issue by SayaMadness** [Gaerisson/Gmod-Custom-Menu#4]
Is it possible to remove the small server list at the bottom? It's kind of annoying me since i live near Russia and i keep getting these annoying DarkRP and Sandbox servers there.

**Comment by Gaerisson** [comment]
This server list in your favorites servers, if you don't want to see them, remove it from your favorites (in server browser)

**Comment by Gaerisson** [comment]
This server list in your favorites servers, if you don't want to see them, remove them from your favorites list (in server browser)

**Comment by Gaerisson** [comment]
I think I'll develop a software for updating this menu and customise it later !
