### ISSUE TITLE
Error when game start

### ISSUE THREAD

**Issue by Blueberryy** [Gaerisson/Gmod-Custom-Menu#5]
[MENU ERROR] lua/menu/mount/mount.lua:101: attempt to call method 'SetMessage' (a nil value)
  1. v - lua/menu/mount/mount.lua:101
   2. unknown - lua/includes/modules/hook.lua:84

Maybe because of new gmod updates
Update your menu please :)

**Comment by Gaerisson** [comment]
It should be fixed now, thanks for report !
