### ISSUE TITLE
Favorite server list

### ISSUE THREAD

**Issue by LehBel** [Gaerisson/Gmod-Custom-Menu#7]
Button "Connect" have an offset and i cant press this button) I can connect by double-click on server or Original browser(like in CSS) but this looks bad. Pls fix. And button "filter_by_gamemode" same have an offset. My monitor have 1680x1060(16:10). Sry for bad knowledge in English bcs im Russian)

**Comment by LehBel** [comment]
[https://imgur.com/7ovEmj8](url)
screeshot

**Comment by Gaerisson** [comment]
I will take a look at this issue, (for the connect button), about the "filter_by_gamemode" I removed it, the "Go Back" button do the same.

**Comment by LehBel** [comment]
> I will take a look at this issue, (for the connect button), about the "filter_by_gamemode" I removed it, the "Go Back" button do the same.

Hmmm, idk why, but buttons, dissapeared)
Link: https://imgur.com/5MpGisf

**Comment by Gaerisson** [comment]
Yes, with my new update, you need to have the new x64 bit to make it work !
**Update 11/04/20**: You have to enable the beta 'x86-64 - Chromuim + 64-bit binaries' for the menu to work main_menu
![image](https://user-images.githubusercontent.com/25458928/79078499-0e850e00-7d09-11ea-9796-841751fdc2a9.png)
